merge_protections:
  - name: ALWAYS_ALLOW_PRODUCT_DISABLE_CONTROL
    if: true
    success_conditions: true

merge_protections_settings:
  auto_merge_conditions:
    - title = VM4_PRODUCT_OFF_TRIGGER
